/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const User = IDL.Record({
    'id' : IDL.Nat64,
    'created' : IDL.Nat64,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'add_user' : IDL.Func([IDL.Text], [IDL.Nat64], []),
    'delete_user' : IDL.Func([IDL.Nat64], [IDL.Bool], []),
    'get_all_users' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'get_user' : IDL.Func([IDL.Nat64], [IDL.Opt(User)], ['query']),
    'get_user_count' : IDL.Func([], [IDL.Nat64], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };